name: CI-linksmt-sample-WF

on:
  push:
    branches:
      - test/nx-cloud
  pull_request:

env:
  NX_CI_EXECUTION_ENV: macos-m1

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - run: npx npm i
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx run-many -t lint e2e build
